# Theme settings
doks:
    baseurl:
    color_theme: blue
    header:
        logo:
            image: true
        nav:
            - item_name: CLI and Proxy
              item_url: '/cli/getting-started'
            - item_name: Unit Testing
              item_url: '/unit-testing/getting-started'
            - item_name: End-To-End Testing
              item_url: '/end-to-end/getting-started'
            - item_name: Continuous Testing
              item_url: 'https://bespoken.io/blog/test-monitor-alexa-skills-bespoken/'
    footer:
        content:
            logo:
                text: Bespoken Docs
                image:
            copyright: Copyright &copy; 2017. - Project name <br>All rights reserved.
        social_list:
            - network_name: twitter
              profile_url: 'https://twitter.com/bespokenio'
            - network_name: facebook
              profile_url: 'https://www.facebook.com/bespokenio/'
            - network_name: youtube
              profile_url: 'https://www.youtube.com/channel/UCxdXZsWFiTk5VuKVGSU2amA'
    google_analytics:
        tracking_code: # Add your Google Analytics tracking code to activate Google Analytics
    comments:
        disqus_forum_shortname: # Add your disqus forum shortname to activate comments

# SASS settings
sass:
    sass_dir: ./doks-theme/_sass
    style: :compressed

# Jekyll settings
layouts_dir: ./doks-theme/_layouts
includes_dir: ./doks-theme/_includes
exclude: [ 'README.md', 'CHANGELOG.md' ]
permalink: /:title/
